-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: Apr 27, 2019 at 09:24 AM
-- Server version: 5.6.35
-- PHP Version: 7.1.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `gevorg`
--

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `title` text NOT NULL,
  `price` int(11) NOT NULL,
  `image` text NOT NULL,
  `info` text NOT NULL,
  `data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `type` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `title`, `price`, `image`, `info`, `data`, `type`) VALUES
(2, 'Samsung Galaxy S10(Black)', 900, 'https://stuff.co.za/wp-content/uploads/2018/11/Samsung-Galaxy-S10-header.jpg', 'The S10 line comprises four models with various hardware specifications; the main S10 and S10+ respectively feature 6.1 and 6.4-inch 1440p \"Dynamic AMOLED\" displays with HDR10+ support and \"dynamic tone mapping\" technology.[7] The displays have curved sides that slope over the horizontal edges of the device. Unlike previous Samsung phones, their front-facing cameras occupy a rounded cut-out near the top-right of the display, and both models utilize an ultrasonic in-screen fingerprint reader.[5] While providing better performance over the optical in-screen fingerprint readers introduced by other recent phones, they are not compatible with all screen protectors (due to this, the S10 and S10+ are both supplied with a pre-installed plastic screen protector).[5][8]\r\n\r\nInternational models of the S10 utilize the Exynos 9820 system-on-chip, while the U.S., South American and Chinese models utilize the Qualcomm Snapdragon 855.[9][10] The two devices are sold with 128 or 512 GB of internal storage, with the S10+ also being sold in a 1-terabyte model. They respectively contain 3400 and 4100 mAh batteries, supporting Qi inductive charging, and the ability to charge other Qi-compatible devices from their own battery power.[11][5]\r\n\r\nThe S10 features a multi-lens rear-facing camera setup; it retains the dual-aperture 12-megapixel and 12-megapixel telephoto lenses of the Galaxy S9+, but also adds a 16-megapixel ultra-wide-angle lens. The front-facing camera on the S10+ is accompanied by a second RGB depth sensor, which Samsung stated would help improve the quality of photo effects and augmented reality image filters. Both sets of cameras support 4K video recording and HDR10+. The camera software includes a new \"Shot Suggestion\" feature to assist users, \"Artistic Live Filters\", as well as the ability to post directly to Instagram posts and stories.[12][13][14][15]\r\n\r\nAlongside the main S10 and S10+, Samsung also unveiled two additional models. The S10e is a downsized version of the S10, featuring a smaller, flat 5.8-inch 1080p display with no curved edges. Its fingerprint reader is contained within the power button on the side rather than in-display, and it excludes the 12-megapixel telephoto camera of the S10 (but still includes the dual-aperture 12-megapixel and 16-megapixel ultra-wide-angle sensors).[16] In addition, Samsung announced a larger, phablet-sized premium model known as the S10 5G: it features support for 5G wireless networks, a 6.7-inch display, 256 GB of non-expandable storage, additional 3D time-of-flight cameras on both the front and rear, and a 4,500 mAh battery. This model will temporarily be exclusive to Verizon Wireless on launch in 2019 before expanding to other carriers in the weeks after launch.', '2019-04-26 15:37:56', ''),
(3, 'Samsung Galaxy S10e', 750, 'https://www.xda-developers.com/files/2019/02/Samsung-Galaxy-S10e.jpg', 'Samsung Galaxy S10e is a Android smartphones manufactured and launched by Samsung. The Samsung Galaxy S10e launch price started at $749. Samsung Galaxy S10e have 5 Colors Prism White, Prism Black, Prism Green, Prism Blue, Prism Yellow.Dimensions & Weight\r\nDimensions: 142.2 x 69.9 x 7.9 mm\r\nWeight: 150 g\r\n\r\nDisplay\r\nType – Dynamic AMOLED capacitive touchscreen, 16M colors\r\nSize -5.8 inches\r\nResolution – 1080 x 2280 pixels, 19:9 ratio (~438 ppi density)\r\n\r\nProtection – Corning Gorilla Glass 5, HDR10+, Always-on display\r\n\r\nColors\r\nPrism White, Prism Black, Prism Green, Prism Blue, Prism Yellow.\r\n\r\nCamera\r\nFRONT CAMERA\r\n\r\nDual – 12 MP, f/1.5-2.4, 26mm (wide), 1/2.55&#8243;, 1.4µm, Dual Pixel PDAF, OIS\r\n16 MP, f/2.2, 12mm (ultrawide), 1.0µm\r\nFeatures – LED flash, auto-HDR, panorama\r\nVideo – 2160p@60fps, 1080p@240fps, 720p@960fps, HDR, dual-video rec.\r\n\r\nREAR CAMERA\r\n\r\nSingle – 10 MP, f/1.9, 26mm (wide), 1.22µm, Dual Pixel PDAF\r\nFeatures – Dual video call, Auto-HDR\r\nVideo – 2160p@30fps, 1080p@30fps\r\n\r\nFeatures\r\nSensors – Fingerprint (side-mounted), accelerometer, gyro, proximity, compass, barometer, ANT+\r\nBixby natural language commands and dictation.\r\n\r\nOS\r\nAndroid 9 (Pie) \r\n\r\nMemory\r\n6GB RAM with 128GB internal storage And 8GB RAM with 256GB internal storage.', '2019-04-26 15:40:55', ''),
(5, 'Samsung Galaxy S10 Plus', 1000, 'https://www.unlockplus.com/blog/wp-content/uploads/2018/12/samsung-s10-rumors.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 15:49:16', ''),
(6, 'Samsung Galaxy S9', 600, 'https://i.gadgets360cdn.com/products/large/1519585124_635_samsung_galaxy_s9_blue.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 15:50:42', ''),
(7, 'Samsung Galaxy S9 Plus', 700, 'https://cdn57.androidauthority.net/wp-content/uploads/2018/02/android-authority-samsung-galaxy-s9-plus-leak.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 15:51:34', ''),
(8, 'Samsung Galaxy Fold', 1800, 'https://cdn.extra.ie/wp-content/uploads/2019/02/21113916/Samsung-Galaxy-Fold_5-1200x700.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 15:54:52', ''),
(9, 'iPhone XS Max', 1100, 'https://brain-images-ssl.cdn.dixons.com/0/5/10185950/u_10185950.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 15:56:59', ''),
(10, 'iphone XS', 1000, 'https://i.gadgets360cdn.com/products/large/1536782640_635_iphone_xs.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:05:23', ''),
(11, 'iphone XR(Coral)', 750, 'https://olcha.uz/image/original/enRR2a24LAMqXxCTYygAIHyjNO2CaY62KVk845TTuuzakhzTmcVouZFieDmx.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:06:45', ''),
(12, 'iPhone 8 Plus', 699, 'https://cdn.movertix.com/media/catalog/product/cache/image/1200x/a/p/apple-iphone-8-plus-64-gb-gris-espacial-0190198454140.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:17:41', ''),
(13, 'iphone 8', 599, 'https://www.phonefinity.net/wp-content/uploads/iphone-8-gold-back.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:18:37', ''),
(14, 'iPhone 7', 449, 'https://n3.sdlcdn.com/imgs/c/2/9/Apple-iPhone-7-128GB-and-SDL759064903-2-98b4d.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:20:14', ''),
(15, 'Google Pixel 3 XL', 699, 'https://i-cdn.phonearena.com/images/phones/73494-xlarge/Google-Pixel-3-XL.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:22:48', ''),
(16, 'Huawei P30 Pro', 999, 'https://www.mobiledokan.com/wp-content/uploads/2019/03/Huawei-P30-Pro-Crystal.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:29:19', ''),
(17, 'Huawei P30', 695, 'https://www.stuff.tv/sites/stuff.tv/files/brands/Huawei/P30-Pro/p30-pro-geskin-render.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:54:28', ''),
(18, 'Huawei Mate X', 1699, 'https://boygeniusreport.files.wordpress.com/2019/02/huawei-mate-x-mwc-2019-hands-on-for-real-8-1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 16:58:12', ''),
(19, 'HP Omen 15t', 750, 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c06052372.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:02:16', ''),
(20, 'HP Omen 17t', 950, 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c05535743.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:03:38', ''),
(21, 'HP ENVY Laptop 17t', 800, 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c05981086.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:05:00', ''),
(22, 'HP ProBook 645 G4 Notebook', 859, 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c05935137.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:06:31', ''),
(23, '15 inch MacBook Pro - Space Gray', 2399, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/m/bp/mbp15touch/space/mbp15touch-space-select-201807?wid=904&hei=840&fmt=jpeg&qlt=95&.v=1529520056969', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:08:43', ''),
(24, 'MacBook Air - Space Gray', 1399, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/m/ac/macbook/air/macbook-air-space-gray-config-201810?wid=539&hei=312&fmt=jpeg&qlt=95&.v=1539386809517', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:10:23', ''),
(25, 'iMac Pro', 4999, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ma/imacpro/27/imacpro-27-retina-selection-hero?wid=452&hei=420&fmt=jpeg&qlt=95&op_usm=0.5,0.5&.v=1511982294002', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:11:28', ''),
(26, '27 inch iMac with Retina 5K display', 1499, 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ma/imac/27/imac-27-cto-hero-201903?wid=627&hei=522&fmt=jpeg&qlt=95&.v=1553120926412', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:12:45', ''),
(27, 'Dell G7 17 Gaming Laptop', 1530, 'https://i.dell.com/sites/csimages/Video_Imagery/all/g7-15b-17.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:14:49', ''),
(28, 'ALIENWARE 17 GAMING LAPTOP', 1399, 'https://i.dell.com/sites/imagecontent/videos/en/PublishingImages/aw-17-gaming.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:16:56', ''),
(29, 'Dell XPS 15', 1000, 'https://i.dell.com/sites/csimages/Video_Imagery/all/26188-notebooks-xps-15-9570-1280x720.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:18:41', ''),
(30, 'Predator Helios 300', 1300, 'https://static-ecpa.acer.com/media/catalog/product/cache/7/image/1200x/040ec09b1e35df139433887a97daa66f/p/r/predator-helios-300-ph315-51-main_1.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:24:11', ''),
(31, 'Acer Predator Helios 500', 2000, 'https://static-ecpa.acer.com/media/catalog/product/cache/7/image/1200x/040ec09b1e35df139433887a97daa66f/p/r/predator-helios-500-ph517-51_sku_photogallery_01_3.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:25:11', ''),
(32, 'Acer Swift 7', 1700, 'https://static-ecpa.acer.com/media/catalog/product/cache/7/image/1200x/040ec09b1e35df139433887a97daa66f/s/w/swift7_gallery_03.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:26:36', ''),
(33, 'FIFA 19- PlayStation4', 60, 'https://tse1.mm.bing.net/th?id=OIP.unbwVnFrZh6S7K61x4T4rQHaJV&pid=Api&P=0&w=300&h=300', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 17:28:32', ''),
(35, 'Battlefield 1', 50, 'http://static5.gamespot.com/uploads/scale_medium/536/5360430/3058949-untitled-2.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:04:00', ''),
(36, 'Battlefield 5', 60, 'https://www.tapscape.com/wp-content/uploads/2018/05/Battlefield-5-1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:05:20', ''),
(37, 'Call of Duty: Black Ops 4', 60, 'http://gearnuke.com/wp-content/uploads/2018/05/call-of-duty-black-ops-4-image-2.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:06:37', ''),
(38, 'Call of Duty: Black Ops 3', 40, 'http://gearnuke.com/wp-content/uploads/2016/08/Call-of-duty-black-ops-3-1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:07:38', ''),
(39, 'Call of Duty: Infinite Warfare', 30, 'http://cdn.wccftech.com/wp-content/uploads/2016/07/infinitewarfare.png', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:08:30', ''),
(40, 'Call of Duty: WWII', 50, 'http://gameranx.com/wp-content/uploads/2017/05/CALL-OF-DUTY-WWII-4K-Wallpaper-1.jpg', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:09:18', '');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `title` text NOT NULL,
  `image` text NOT NULL,
  `price` int(11) NOT NULL,
  `info` text NOT NULL,
  `data` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `image`, `price`, `info`, `data`) VALUES
(1, 'PlayStation 4 Pro', 'https://media.playstation.com/is/image/SCEA/playstation-4-pro-vertical-product-shot-01-us-07sep16?$TwoColumn_Image$', 415, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:23:31'),
(2, 'Xbox One X', 'https://content.abt.com/media/images/products/BDP_Images/big_CYV00001.jpg', 600, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:24:41'),
(3, 'Xbox One S (Military Version)', 'https://blogs-images.forbes.com/erikkain/files/2016/11/bf1-xbox-one-s.jpg', 300, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:27:36'),
(4, 'PlayStation 4 Slim Gold', 'https://tse2.mm.bing.net/th?id=OIP.G53-We9BqPiupfi8F18uwQHaF3&pid=Api&P=0&w=212&h=168', 160, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:28:28'),
(5, 'PlayStation 4 Slim White', 'https://tse3.mm.bing.net/th?id=OIP.sDXa-X9uJHbU7drHSPc6fAHaHa&pid=Api&P=0&w=300&h=300', 160, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:31:10'),
(6, 'Nintendo Switch', 'https://tse4.mm.bing.net/th?id=OIP.R4hilRv14fFyfTQb_S3iYwHaGk&pid=Api&P=0&w=200&h=179', 300, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:31:58'),
(7, 'PlayStation 3', 'https://www.numberconnect.info/wp-content/uploads/2015/02/ps3.jpg', 80, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:32:55'),
(8, 'PlayStation 3 Slim Blue ', 'https://i.ebayimg.com/images/i/201082122506-0-1/s-l1000.jpg', 120, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:33:31'),
(9, 'Xbox 360', 'https://images-na.ssl-images-amazon.com/images/G/01/aplus/detail-page/B00D9EPI38_img1_lg.jpg', 100, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:34:10'),
(10, 'Apple Watch Series 4', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/4/4/44/alu/44-alu-space-sport-black-nc-s4-1up?wid=470&hei=556&fmt=png-alpha&.v=1549036770374', 429, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\r\n', '2019-04-26 18:50:29'),
(11, 'Apple Watch Hermès', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/4/4/44/hermes/44-hermes-indigo-craie-orange-singletour-s4-1up?wid=470&hei=556&fmt=png-alpha&.v=1541713526101', 1300, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:51:40'),
(12, 'Samsung Gear S3 Frontier', 'http://s7d2.scene7.com/is/image/SamsungUS/003class?$product-details-jpg$', 300, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:52:44'),
(13, 'Apple TV 4K 64GB', 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/a/pp/apple/tv/apple-tv-hero-select-201709?wid=538&amp;amp;hei=535&amp;amp;fmt=jpeg&amp;amp;qlt=95&amp;amp;op_usm=0.5,0.5&amp;amp;.v=1504814112595', 200, 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '2019-04-26 18:53:36');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;
--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
